/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Id = IDL.Nat;
export const ServiceType = IDL.Variant({
  'windowCleaning' : IDL.Null,
  'other' : IDL.Null,
  'endOfLease' : IDL.Null,
  'pestControl' : IDL.Null,
  'carpetCleaning' : IDL.Null,
});
export const Time = IDL.Int;
export const Simplified = IDL.Record({
  'id' : Id,
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Simplified)], ['query']),
  'getSubmissionById' : IDL.Func([Id], [Simplified], ['query']),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
      [Id],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Id = IDL.Nat;
  const ServiceType = IDL.Variant({
    'windowCleaning' : IDL.Null,
    'other' : IDL.Null,
    'endOfLease' : IDL.Null,
    'pestControl' : IDL.Null,
    'carpetCleaning' : IDL.Null,
  });
  const Time = IDL.Int;
  const Simplified = IDL.Record({
    'id' : Id,
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Simplified)], ['query']),
    'getSubmissionById' : IDL.Func([Id], [Simplified], ['query']),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
        [Id],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };